# Generated by Django 6.0.6 on 2026-06-03 20:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ENGINEER', 'Engineer'), ('CLIENT_COMPANY', 'Client company'), ('QUALITY_CONTROLLER', 'Quality controller')], max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180)),
                ('commercial_register', models.CharField(max_length=80)),
                ('contact_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits, spaces, and optional +().- characters.', regex='^\\+?[0-9\\s().-]{7,20}$')])),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='EngineerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=60, unique=True)),
                ('department', models.CharField(max_length=120)),
                ('specialty', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('NETWORKS', 'Networks'), ('HVAC', 'HVAC'), ('PLUMBING', 'Plumbing'), ('MEDICAL_DEVICES', 'Medical devices'), ('SURVEILLANCE', 'Surveillance'), ('SOFTWARE', 'Software'), ('SERVERS', 'Servers'), ('CYBERSECURITY', 'Cybersecurity')], max_length=32)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits, spaces, and optional +().- characters.', regex='^\\+?[0-9\\s().-]{7,20}$')])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='engineers/avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_SITE', 'On site'), ('ON_LEAVE', 'On leave')], default='AVAILABLE', max_length=16)),
                ('experience_years', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('NETWORKS', 'Networks'), ('HVAC', 'HVAC'), ('PLUMBING', 'Plumbing'), ('MEDICAL_DEVICES', 'Medical devices'), ('SURVEILLANCE', 'Surveillance'), ('SOFTWARE', 'Software'), ('SERVERS', 'Servers'), ('CYBERSECURITY', 'Cybersecurity')], max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('location_details', models.TextField()),
                ('description', models.TextField()),
                ('preferred_date', models.DateTimeField()),
                ('is_hazardous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under review'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('WAITING_SPARE_PARTS', 'Waiting spare parts'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NEW', max_length=24)),
                ('assigned_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('waiting_spare_parts_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='maintenance.engineerprofile')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='maintenance.companyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('BEFORE_EXECUTION', 'Before execution'), ('DURING_EXECUTION', 'During execution'), ('AFTER_EXECUTION', 'After execution')], max_length=24)),
                ('image', models.ImageField(upload_to='maintenance/evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='maintenance.maintenancerequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_request_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='maintenance_role_191d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='maintenance_email_4c23e7_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['company_name'], name='maintenance_company_6fd523_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['commercial_register'], name='maintenance_commerc_f480ee_idx'),
        ),
        migrations.AddIndex(
            model_name='engineerprofile',
            index=models.Index(fields=['specialty', 'availability_status'], name='maintenance_special_6bca13_idx'),
        ),
        migrations.AddIndex(
            model_name='engineerprofile',
            index=models.Index(fields=['department'], name='maintenance_departm_6c5add_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status', 'priority'], name='maintenance_status_b5e015_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['issue_type', 'status'], name='maintenance_issue_t_1b5e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['client_company', 'status'], name='maintenance_client__6c43b9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['assigned_engineer', 'status'], name='maintenance_assigne_733ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['created_at'], name='maintenance_created_311a90_idx'),
        ),
        migrations.AddIndex(
            model_name='requestevidence',
            index=models.Index(fields=['request', 'stage'], name='maintenance_request_be0d92_idx'),
        ),
        migrations.AddIndex(
            model_name='requestevidence',
            index=models.Index(fields=['uploaded_at'], name='maintenance_uploade_d30074_idx'),
        ),
    ]
