# Generated by Django 6.0.6 on 2026-06-04 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits, spaces, and optional +().- characters.', regex='^\\+?[0-9\\s().-]{7,20}$')])),
                ('message', models.TextField(max_length=1600)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CLOSED', 'Closed')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='maintenance_status_18a0d3_idx'), models.Index(fields=['email'], name='maintenance_email_91ce40_idx'), models.Index(fields=['company_name'], name='maintenance_company_6e85d7_idx')],
            },
        ),
    ]
