# Generated by Django 6.0.6 on 2026-06-08 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_publiccontactinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits, spaces, and optional +().- characters.', regex='^\\+?[0-9\\s().-]{7,20}$')])),
                ('specialty', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('NETWORKS', 'Networks'), ('HVAC', 'HVAC'), ('PLUMBING', 'Plumbing'), ('MEDICAL_DEVICES', 'Medical devices'), ('SURVEILLANCE', 'Surveillance'), ('SOFTWARE', 'Software'), ('SERVERS', 'Servers'), ('CYBERSECURITY', 'Cybersecurity')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['specialty'], name='maintenance_special_0f8f47_idx'), models.Index(fields=['created_at'], name='maintenance_created_267438_idx')],
            },
        ),
    ]
