# Generated by Django 6.0.6 on 2026-06-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_publicengineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_public_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='maintenance.publicengineer'),
        ),
    ]
