# Generated by Django 6.0.6 on 2026-06-10 00:43

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenancerequest_cost'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publicengineer',
            name='maintenance_special_0f8f47_idx',
        ),
        migrations.AddField(
            model_name='publicengineer',
            name='availability_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='publicengineer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='engineers/public/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='publicengineer',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='publicengineer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='publicengineer',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='publicengineer',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publicengineer',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='publicengineer',
            index=models.Index(fields=['specialty', 'is_available'], name='maintenance_special_861640_idx'),
        ),
    ]
