# Generated by Django 6.0.6 on 2026-06-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_remove_publicengineer_maintenance_special_0f8f47_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicengineer',
            name='device_id_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publicengineer',
            name='device_label',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='publicengineer',
            name='device_last_seen_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
