# Generated by Django 6.0.6 on 2026-06-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_publicengineer_device_id_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=240)),
                ('provider', models.CharField(choices=[('CLOUDFLARE', 'Cloudflare Email'), ('SMTP', 'SMTP'), ('DISABLED', 'Disabled')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_notifications', to='maintenance.engineerprofile')),
                ('public_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_notifications', to='maintenance.publicengineer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_notifications', to='maintenance.maintenancerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='maintenance_status_200a03_idx'), models.Index(fields=['request', 'created_at'], name='maintenance_request_e505b2_idx')],
            },
        ),
    ]
