# Generated by Django 6.0.6 on 2026-06-11 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_assignmentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('COMPANY', 'Company'), ('ENGINEER', 'Engineer')], max_length=16)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('REGISTER', 'Register')], max_length=16)),
                ('code_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('NOTE', 'Note'), ('STATUS', 'Status update'), ('ACCEPTED', 'Accepted'), ('AUTO_ASSIGNED', 'Auto assigned')], max_length=24)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['is_archived'], name='maintenance_is_arch_d3a647_idx'),
        ),
        migrations.AddIndex(
            model_name='portalotpchallenge',
            index=models.Index(fields=['email', 'role', 'created_at'], name='maintenance_email_5d27c4_idx'),
        ),
        migrations.AddIndex(
            model_name='portalotpchallenge',
            index=models.Index(fields=['expires_at'], name='maintenance_expires_a7e29f_idx'),
        ),
        migrations.AddField(
            model_name='requestactivity',
            name='public_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_activities', to='maintenance.publicengineer'),
        ),
        migrations.AddField(
            model_name='requestactivity',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='maintenance.maintenancerequest'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['request', 'created_at'], name='maintenance_request_b2c27c_idx'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['public_engineer', 'created_at'], name='maintenance_public__9b871f_idx'),
        ),
    ]
